---
title: 'Six little data points and one huge story'
author: "Ben Nolting"
date: 2012-08-08
slug: six-little-data-points-and-one-huge-story
categories: ['Disease', 'Research Highlights']
draft: false
---

It has been an exciting summer in science news. In early July, CERN [announced](http://www.guardian.co.uk/science/2012/jul/04/higgs-boson-cern-scientists-discover) the probable discovery of a Higgs-like particle at the Large Hadron Collider, filling a long open hole in the standard model of physics. On Sunday, the Curiosity rover [successfully executed](http://www.guardian.co.uk/science/2012/aug/06/mars-curiosity-rover-nasa-perfect-landing) a phenomenally difficult landing on Mars. 

Sandwiched between these headline-grabbing events, a story of arguably equal significance has been overshadowed: [evidence](http://www.ajtmh.org/content/87/2/206.full) from the remote Amazon that unvaccinated humans can develop antibodies to rabies.

Rabies is a scary disease ([jokes on _The Office_](http://en.wikipedia.org/wiki/Fun_Run) notwithstanding). It causes [approximately 55,000 deaths annually](http://en.wikipedia.org/wiki/Prevalence_of_rabies). Victims suffer anxiety, hallucinations, delirium, paralysis and eventually death. It is hard to imagine a more horrific way to die. 

In the August issue of the American Journal of Tropical Medicine and Hygiene (ATMJH), Amy Gilbert of the Center for Disease Control and several colleagues [report the results](http://www.ajtmh.org/content/87/2/206.full) of a study in Peru. In 63 individuals tested, 7 showed presence of rabies neutralizing antibodies (rVNAs). Only one of these individuals had been vaccinated. In the rainforests of Peru, vampire bat bites present a serious threat for rabies infection. 113 human rabies cases reported between 1996 and 2010 in Peru have been associated with vampire bats. The six unvaccinated, rVNA positive individuals identified by Gilbert’s study are remarkable, because they show that some people can survive rabies without treatment. 

How did these people survive rabies? Do they have some genetic advantage that allows them to overcome infection? Are they immune to further infection? Will this discovery advance the global battle against rabies? These questions remain to be answered, but Gilbert and her colleagues are on the case. 

Rodney Willoughby Jr., the developer of the [Milwaukee protocol experimental treatment](http://en.wikipedia.org/wiki/Milwaukee_protocol) for rabies, has an [editorial](http://www.ajtmh.org/content/87/2/205.full) on Gilbert’s paper in the same issue of AJTMH. Willoughby writes:

>Knowing that there is a continuum of disease, even for infectious diseases like rabies, should push us harder to try for cures when confronted by so-called untreatable infectious diseases or intoxications. 

Let’s hope that researchers like Gilbert continue to push harder, and are ultimately successful, in their effort to combat a terrible disease.