---
title: "Zing! Mathematica one-liners"
author: "Ben Nolting"
date: 2012-09-21
slug: zing
categories: ['mathematica', 'programming-tips']
draft: false
---

I love the elegant simplicity of programming in Mathematica. There is something undeniably beautiful about accomplishing something complex in a concise chunk of code. A famous Mathematica mantra is, "if you are using a For loop, you are probably doing it wrong." I encourage Mathematica programmers to keep that in mind. 

To illustrate the efficiency of Mathematica code, I'd like to draw your attention to the recent results of [Wolfram's "One-Liner Competition"](http://blog.wolfram.com/2012/09/20/mathematica-experts-live-one-liner-competition-and-the-winners-are/). Each program in the competition is 140 characters or less. Yes, that's right... tweetable programs. You can watch screencasts of the winner and honorable mentions [here](http://www.wolfram.com/broadcast/video.php?channel=282).

For those who work in biological modelling, I recommend checking [Yves Klett's](http://www.ifb.uni-stuttgart.de/mitarbeiter?id=35) entry. It gives a new meaning to the old modelling punchline "assume all cows are spheres".